AWSTemplateFormatVersion: "2010-09-09"
Description: SSL Certificate issued by ACM.
Parameters:
  DomainName:
    Type: String
    Description: |-
      Top level domain where you want your certificate to be issued.
       For example: example.com
  AccountName:
    Type: 'String'
    Description: 'Name of the account where the template is deployed to.'

Conditions:
  IsProduction:
    Fn::Equals: [ !Ref 'AccountName', 'randomlunch' ]
  NotProduction:
    Fn::Not:
      - Fn::Equals: [ !Ref 'AccountName', 'randomlunch' ]
Resources:
  DomainCertificateDev:
    Type: 'AWS::CertificateManager::Certificate'
    Condition: 'NotProduction'
    Properties:
      DomainName: !Sub "dev.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "dev.${DomainName}"
          ValidationDomain: !Sub "${DomainName}"
  DomainCertificateDevWildCard:
    Type: 'AWS::CertificateManager::Certificate'
    Condition: 'NotProduction'
    Properties:
      DomainName: !Sub "*.dev.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "*.dev.${DomainName}"
          ValidationDomain: !Sub "${DomainName}"
  DomainCertificateProd:
    Type: 'AWS::CertificateManager::Certificate'
    Condition: 'IsProduction'
    Properties:
      DomainName: !Sub "${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "${DomainName}"
          ValidationDomain: !Sub "${DomainName}"
  DomainCertificateProdWildCard:
    Type: 'AWS::CertificateManager::Certificate'
    Condition: 'IsProduction'
    Properties:
      DomainName: !Sub "*.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "*.${DomainName}"
          ValidationDomain: !Sub "${DomainName}"
Outputs:
  # The different arn-s that you'll have to provide for your CloudFront distribution to make it secure.
  DomainCertificateDevArn:
    Value: !Ref DomainCertificateDev
    Condition: 'NotProduction'
  DomainCertificateDevWildCardArn:
    Value: !Ref DomainCertificateDevWildCard
    Condition: 'NotProduction'
  DomainCertificateProdArn:
    Value: !Ref DomainCertificateProd
    Condition: 'IsProduction'
  DomainCertificateProdWildCardArn:
    Value: !Ref DomainCertificateProdWildCard
    Condition: 'IsProduction'