# The name of the app.
name: 'randomlunch-ui'

accounts:
  - name: 'randomlunchdev'
    account_number: '952080297105'
  - name: 'randomlunch'
    account_number: '206670076487'

templates:
  stage:
    # Relative or absolute path to a directory containing CloudFormation
    # templates for the stage.
    path: 'cloudformation'
    # `params` is for injecting any required parameters to the top-level
    # CloudFormation stack.
    params:
      Stage: '{{ stage.name }}'
      APIPrefix: 'rnd'
      ApplicationName: 'randomlunch'
      DomainName: 'randomlunch.burib.net'
      # randomlunch.burib.net under randomlunchdev
      CertificateArnProd: 'arn:aws:acm:us-east-1:206670076487:certificate/1da3189e-0d21-44f2-971c-277903aee8c7'
      # dev.randomlunch.burib.net under randomlunchdev
      CertificateArnDev: 'arn:aws:acm:us-east-1:952080297105:certificate/c3a1cb83-84e1-4ece-813d-dc4caa9a5380'
      # *.dev.randomlunch.burib.net under randomlunchdev
      CertificateArnDevWildcard: 'arn:aws:acm:us-east-1:952080297105:certificate/ea0a0d96-77e5-4e76-b0f7-a9a8719cdf5b'
stages:
  # "default" contains configs which are used for custom ad-hoc stages.
  # For example, you may want to deploy a custom test stage for yourself,
  # such as "alice" or "bob".
  # As a result,
  default:
    account: 'randomlunchdev'
    region: 'eu-west-1'
  dev:
    account: 'randomlunchdev'
    region: 'eu-west-1'
    # Protected prevents certain destructive actions from being run, unless
    # you are really sure you want to do. Default is false.
    protected: true
  prod:
    account: 'randomlunch'
    region: 'eu-west-1'
    protected: true
services:
  # The section can contain multiple services, if you need the separation.
  ui:
    type: 's3'
    # Destination bucket where published files are to be stored:
    bucket_name: '{{ stage.name }}-{{ ApplicationName }}-ui'
    # Local directory containing files to be published in S3:
    build:
      working_dir: '.'
      dist_dir: 'dist'