AWSTemplateFormatVersion: "2010-09-09"
Description: SSL Certificates issued by ACM.
Parameters:
  DomainName:
    Type: String
    Description: |-
      Top level domain where you want your certificate to be issued.
       For example: example.com
  #TODO: add validation. ( domain name without protocol )
Resources:
  DomainCertificateProd:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub "${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "${DomainName}"
          ValidationDomain: !Sub "${DomainName}"
  DomainCertificateProdWildCard:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub "*.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "*.${DomainName}"
          ValidationDomain: !Sub "${DomainName}"
Outputs:
  # The different arn-s that you'll have to provide for your CloudFront distribution to make it secure.
  DomainCertificateProdArn:
    Value: !Ref DomainCertificateProd
  DomainCertificateProdWildCardArn:
    Value: !Ref DomainCertificateProdWildCard